-- Additional catalog resources to reach the 30–40 item target. Run after 002_catalog.sql.

insert into public.products (
  slug, title, description, short_summary, content_type, provider, source_url,
  license_info, category, difficulty, duration_minutes, skills, prerequisites,
  learning_outcomes, career_goals, price_label, is_external, vector_sync_status
)
values
(
  'data-pipelines-for-ml',
  'Data Pipelines for ML',
  'An original module on collecting, cleaning, and preparing data for machine learning workflows without over-engineering the pipeline.',
  'Build reliable data flows before training models.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Data Foundations', 'Intermediate', 300,
  '["data pipelines", "ETL", "pandas", "feature stores"]'::jsonb,
  '["SQL for Product Builders"]'::jsonb,
  '["Design a small ETL workflow", "Validate data quality gates", "Prepare features for downstream ML"]'::jsonb,
  '["Data/ML Foundations", "AI Engineer"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'ml-model-evaluation-basics',
  'ML Model Evaluation Basics',
  'Learn how to measure whether a model actually helps users—metrics, baselines, error analysis, and when to stop tuning.',
  'Evaluate models with product-minded rigor.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Data Foundations', 'Intermediate', 240,
  '["evaluation", "metrics", "error analysis", "baselines"]'::jsonb,
  '["Data Pipelines for ML"]'::jsonb,
  '["Pick metrics aligned to user outcomes", "Run a simple error analysis", "Compare against a meaningful baseline"]'::jsonb,
  '["Data/ML Foundations", "AI Engineer"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'pandas-data-wrangling',
  'Pandas Data Wrangling',
  'Hands-on module for tabular data: filtering, grouping, merging, and reshaping—the daily work of data/ML builders.',
  'Manipulate real datasets with confidence.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Data Foundations', 'Beginner', 280,
  '["pandas", "data cleaning", "Python", "CSV"]'::jsonb,
  '["Python Foundations for Builders"]'::jsonb,
  '["Load and inspect tabular data", "Clean messy columns", "Aggregate for analysis"]'::jsonb,
  '["Data/ML Foundations", "Backend Developer"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'deploy-ai-api-to-production',
  'Deploy an AI API to Production',
  'Project track for packaging a FastAPI service with health checks, environment config, and a Render deployment path.',
  'Ship your AI feature behind a real URL.',
  'project', 'SkillOrbit', null, 'Original SkillOrbit project track',
  'AI Product Building', 'Advanced', 480,
  '["deployment", "FastAPI", "Render", "health checks"]'::jsonb,
  '["FastAPI API Foundations", "Production RAG Systems"]'::jsonb,
  '["Configure production environment variables", "Deploy a web service", "Verify health and smoke tests"]'::jsonb,
  '["Production AI Product Builder", "Backend Developer", "AI Engineer"]'::jsonb,
  'Free project track', false, 'pending'
),
(
  'prompt-engineering-for-products',
  'Prompt Engineering for Products',
  'Practical prompting patterns for product features: structured outputs, guardrails, few-shot examples, and cost control.',
  'Write prompts that survive real users.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Generative AI', 'Intermediate', 200,
  '["prompting", "structured output", "guardrails", "LLMs"]'::jsonb,
  '["Embeddings and Semantic Search"]'::jsonb,
  '["Design prompts with explicit output schemas", "Add validation after generation", "Reduce token waste"]'::jsonb,
  '["Generative AI Builder", "AI Engineer", "Production AI Product Builder"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'vector-database-patterns',
  'Vector Database Patterns',
  'Patterns for collections, payload filters, hybrid search, and sync status—the architecture behind SkillOrbit retrieval.',
  'Design vector indexes that match product needs.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Generative AI', 'Intermediate', 260,
  '["vector databases", "Qdrant", "payload filters", "dual-write"]'::jsonb,
  '["Embeddings and Semantic Search"]'::jsonb,
  '["Model catalog-to-vector sync", "Filter retrieval by metadata", "Handle sync failures safely"]'::jsonb,
  '["AI Engineer", "Generative AI Builder"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'backend-authentication-patterns',
  'Backend Authentication Patterns',
  'Session cookies, JWT verification, role guards, and RLS—how SkillOrbit protects learner and admin routes.',
  'Secure APIs without exposing service keys.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Backend Development', 'Intermediate', 220,
  '["authentication", "JWT", "RLS", "sessions"]'::jsonb,
  '["FastAPI API Foundations"]'::jsonb,
  '["Verify tokens server-side", "Separate learner and admin access", "Never leak secrets to the browser"]'::jsonb,
  '["Backend Developer", "Production AI Product Builder"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'rest-api-design-checklist',
  'REST API Design Checklist',
  'A concise checklist for routes, errors, pagination, versioning, and documentation that judges can follow.',
  'Design APIs that other builders trust.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Backend Development', 'Intermediate', 180,
  '["REST", "API design", "OpenAPI", "errors"]'::jsonb,
  '["FastAPI API Foundations"]'::jsonb,
  '["Apply consistent error shapes", "Document endpoints clearly", "Choose sensible resource naming"]'::jsonb,
  '["Backend Developer", "AI Engineer"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'learning-path-ai-engineer',
  'AI Engineer Learning Path',
  'A curated sequence from Python foundations through RAG, agents, and shipping an AI product—SkillOrbit original path metadata.',
  'A structured orbit toward AI engineering.',
  'learning_path', 'SkillOrbit', null, 'Original SkillOrbit learning path',
  'Career Paths', 'Beginner', 2400,
  '["AI engineering", "RAG", "Python", "deployment"]'::jsonb,
  '[]'::jsonb,
  '["Follow a coherent skill progression", "Connect modules to projects", "Prepare for capstone builds"]'::jsonb,
  '["AI Engineer"]'::jsonb,
  'Free learning path', false, 'pending'
),
(
  'learning-path-backend-developer',
  'Backend Developer Learning Path',
  'From Python and SQL through FastAPI, HTTP fundamentals, auth patterns, and deployment.',
  'Build reliable backends step by step.',
  'learning_path', 'SkillOrbit', null, 'Original SkillOrbit learning path',
  'Career Paths', 'Beginner', 2100,
  '["Python", "FastAPI", "SQL", "HTTP"]'::jsonb,
  '[]'::jsonb,
  '["Master core backend skills", "Ship a documented API", "Understand production basics"]'::jsonb,
  '["Backend Developer"]'::jsonb,
  'Free learning path', false, 'pending'
),
(
  'learning-path-generative-ai',
  'Generative AI Builder Path',
  'Embeddings, semantic search, prompting, RAG projects, and agent workflows for LLM-powered features.',
  'Build generative features with grounding.',
  'learning_path', 'SkillOrbit', null, 'Original SkillOrbit learning path',
  'Career Paths', 'Intermediate', 2200,
  '["LLMs", "RAG", "embeddings", "agents"]'::jsonb,
  '["Python Foundations for Builders"]'::jsonb,
  '["Design grounded generative features", "Evaluate retrieval quality", "Ship a RAG demo"]'::jsonb,
  '["Generative AI Builder"]'::jsonb,
  'Free learning path', false, 'pending'
),
(
  'learning-path-data-ml-foundations',
  'Data/ML Foundations Path',
  'SQL, pandas, pipelines, evaluation, and the data thinking behind ML products.',
  'Strong data foundations for ML work.',
  'learning_path', 'SkillOrbit', null, 'Original SkillOrbit learning path',
  'Career Paths', 'Beginner', 2000,
  '["SQL", "pandas", "evaluation", "pipelines"]'::jsonb,
  '[]'::jsonb,
  '["Query and model product data", "Prepare datasets responsibly", "Measure model usefulness"]'::jsonb,
  '["Data/ML Foundations"]'::jsonb,
  'Free learning path', false, 'pending'
),
(
  'learning-path-production-ai-product',
  'Production AI Product Builder Path',
  'End-to-end product skills: auth, catalog, vectors, recommendations, email, and deployment.',
  'Turn AI ideas into demo-ready products.',
  'learning_path', 'SkillOrbit', null, 'Original SkillOrbit learning path',
  'Career Paths', 'Advanced', 2600,
  '["product design", "RAG", "deployment", "observability"]'::jsonb,
  '["FastAPI API Foundations"]'::jsonb,
  '["Integrate AI into a full app", "Explain recommendations to users", "Harden for demo day"]'::jsonb,
  '["Production AI Product Builder"]'::jsonb,
  'Free learning path', false, 'pending'
),
(
  'scikit-learn-user-guide',
  'scikit-learn User Guide',
  'Official scikit-learn documentation for classical ML: preprocessing, model selection, and evaluation on tabular data.',
  'Official reference for practical ML in Python.',
  'documentation', 'scikit-learn',
  'https://scikit-learn.org/stable/user_guide.html',
  'BSD license; follow the source terms',
  'Data Foundations', 'Intermediate', 600,
  '["scikit-learn", "ML", "classification", "regression"]'::jsonb,
  '["Pandas Data Wrangling"]'::jsonb,
  '["Train baseline models", "Use cross-validation", "Navigate official sklearn docs"]'::jsonb,
  '["Data/ML Foundations", "AI Engineer"]'::jsonb,
  'Free official resource', true, 'pending'
),
(
  'openai-embeddings-guide',
  'OpenAI Embeddings Guide',
  'Conceptual guide to embeddings and semantic search from OpenAI—useful context even when routing through Mesh.',
  'Understand embedding use cases and limits.',
  'documentation', 'OpenAI',
  'https://platform.openai.com/docs/guides/embeddings',
  'OpenAI documentation; follow the source terms',
  'Generative AI', 'Beginner', 120,
  '["embeddings", "semantic search", "vectors"]'::jsonb,
  '[]'::jsonb,
  '["Explain why embeddings help retrieval", "Choose embedding use cases", "Avoid common pitfalls"]'::jsonb,
  '["Generative AI Builder", "AI Engineer"]'::jsonb,
  'Free official resource', true, 'pending'
),
(
  'langchain-rag-tutorial',
  'LangChain RAG Tutorial',
  'Open tutorial walking through retrieval-augmented generation concepts—compare patterns with SkillOrbit approach.',
  'Open walkthrough of RAG building blocks.',
  'tutorial', 'LangChain',
  'https://python.langchain.com/docs/tutorials/rag/',
  'LangChain docs license; follow the source terms',
  'Generative AI', 'Intermediate', 360,
  '["RAG", "LangChain", "retrieval", "chains"]'::jsonb,
  '["Embeddings and Semantic Search"]'::jsonb,
  '["Map tutorial steps to your stack", "Identify reusable RAG patterns"]'::jsonb,
  '["Generative AI Builder", "AI Engineer"]'::jsonb,
  'Free open tutorial', true, 'pending'
),
(
  'docker-for-app-developers',
  'Docker for App Developers',
  'Original module on container basics for developers who need reproducible deploys without becoming infra specialists.',
  'Containerize apps for consistent deploys.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'AI Product Building', 'Intermediate', 240,
  '["Docker", "containers", "deployment", "images"]'::jsonb,
  '["FastAPI API Foundations"]'::jsonb,
  '["Build a minimal image", "Run a container locally", "Connect containers to env config"]'::jsonb,
  '["Production AI Product Builder", "Backend Developer"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'behavioral-analytics-for-learners',
  'Behavioral Analytics for Learners',
  'How to capture batched events, dwell time, and search intent without blocking UX—mirrors SkillOrbit tracking design.',
  'Ethical, lightweight behavior signals.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'AI Product Building', 'Intermediate', 200,
  '["analytics", "event tracking", "privacy", "batching"]'::jsonb,
  '["Backend Authentication Patterns"]'::jsonb,
  '["Design a batched event API", "Bound metadata safely", "Explain signals to users"]'::jsonb,
  '["Production AI Product Builder", "AI Engineer"]'::jsonb,
  'Free learning module', false, 'pending'
)
on conflict (slug) do nothing;
