-- Expand catalog toward ~80 resources. Run after 012_user_progress.sql.

insert into public.products (
  slug, title, description, short_summary, content_type, provider, source_url,
  license_info, category, difficulty, duration_minutes, skills, prerequisites,
  learning_outcomes, career_goals, price_label, is_external, vector_sync_status
)
values
(
  'langchain-expression-language',
  'LangChain Expression Language',
  'Official guide to LCEL chains for production agent workflows.',
  'Compose LLM chains with a declarative API.',
  'documentation', 'LangChain', 'https://python.langchain.com/docs/concepts/lcel/',
  'LangChain documentation', 'Agentic AI', 'Intermediate', 120,
  '["LangChain", "LCEL", "agents"]'::jsonb, '[]'::jsonb,
  '["Read chain composition patterns", "Map LCEL to agent steps"]'::jsonb,
  '["AI Engineer", "Generative AI Builder"]'::jsonb,
  'Official documentation', true, 'pending'
),
(
  'openai-function-calling-guide',
  'Tool Use and Function Calling',
  'Structured tools, schemas, and validation for reliable agents.',
  'Wire tools into LLM calls safely.',
  'tutorial', 'SkillOrbit', null, 'Original SkillOrbit tutorial',
  'Agentic AI', 'Intermediate', 180,
  '["function calling", "tools", "JSON schema"]'::jsonb,
  '["Prompt Engineering for Products"]'::jsonb,
  '["Define tool schemas", "Validate model tool args"]'::jsonb,
  '["AI Engineer", "Generative AI Builder"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'build-evaluation-harness',
  'Build an LLM Evaluation Harness',
  'Golden-set tests and retrieval quality metrics before shipping agents.',
  'Test agents before users do.',
  'project', 'SkillOrbit', null, 'Original SkillOrbit project track',
  'AI Product Building', 'Advanced', 360,
  '["evaluation", "testing", "RAG metrics"]'::jsonb,
  '["ML Model Evaluation Basics"]'::jsonb,
  '["Create a golden question set", "Score retrieval precision"]'::jsonb,
  '["AI Engineer", "Production AI Product Builder"]'::jsonb,
  'Free project track', false, 'pending'
),
(
  'huggingface-transformers-docs',
  'Hugging Face Transformers',
  'Official docs for models, tokenizers, and inference pipelines.',
  'Run open models locally or via API.',
  'documentation', 'Hugging Face', 'https://huggingface.co/docs/transformers/index',
  'Hugging Face documentation', 'Generative AI', 'Intermediate', 150,
  '["transformers", "tokenizers", "inference"]'::jsonb, '[]'::jsonb,
  '["Load a pretrained model", "Run a text pipeline"]'::jsonb,
  '["AI Engineer", "Data/ML Foundations"]'::jsonb,
  'Official documentation', true, 'pending'
),
(
  'async-python-for-agents',
  'Async Python for Agents',
  'Concurrency patterns for FastAPI agents with httpx and background tasks.',
  'Keep agent APIs responsive under load.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Backend Engineering', 'Intermediate', 220,
  '["asyncio", "httpx", "FastAPI"]'::jsonb,
  '["Python Foundations for Builders"]'::jsonb,
  '["Use async HTTP clients", "Avoid blocking the event loop"]'::jsonb,
  '["AI Engineer", "Backend Developer"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'coursera-ml-specialization-overview',
  'Machine Learning Specialization (overview)',
  'Curated pointer to Andrew Ng ML specialization for classical ML foundations.',
  'Classical ML foundations from a trusted MOOC.',
  'external_course', 'Coursera', 'https://www.coursera.org/specializations/machine-learning-introduction',
  'Coursera course listing', 'Data Foundations', 'Beginner', 600,
  '["machine learning", "supervised learning"]'::jsonb, '[]'::jsonb,
  '["Pick a structured ML curriculum"]'::jsonb,
  '["AI Engineer", "Data/ML Foundations"]'::jsonb,
  'External · free audit', true, 'pending'
),
(
  'postgresql-jsonb-patterns',
  'PostgreSQL JSONB Patterns',
  'JSONB indexing and querying for product metadata and event payloads.',
  'Model flexible product data in Postgres.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Backend Engineering', 'Intermediate', 200,
  '["PostgreSQL", "JSONB", "SQL"]'::jsonb,
  '["SQL for Product Builders"]'::jsonb,
  '["Query JSONB fields efficiently", "Add GIN indexes where needed"]'::jsonb,
  '["Backend Developer", "Production AI Product Builder"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'fastapi-security-guide',
  'FastAPI Security',
  'Official OAuth2, scopes, and dependency injection for protected routes.',
  'Harden APIs beyond basic login.',
  'documentation', 'FastAPI', 'https://fastapi.tiangolo.com/tutorial/security/',
  'FastAPI documentation', 'Backend Engineering', 'Intermediate', 120,
  '["FastAPI", "OAuth2", "security"]'::jsonb,
  '["FastAPI API Foundations"]'::jsonb,
  '["Apply dependency guards", "Document security in OpenAPI"]'::jsonb,
  '["Backend Developer"]'::jsonb,
  'Official documentation', true, 'pending'
),
(
  'redis-caching-patterns',
  'Caching Patterns for APIs',
  'TTL and invalidation for embeddings, catalog lists, and recommendations.',
  'Cut latency without stale surprises.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Backend Engineering', 'Intermediate', 160,
  '["caching", "TTL", "performance"]'::jsonb,
  '["FastAPI API Foundations"]'::jsonb,
  '["Choose cache keys", "Invalidate on catalog updates"]'::jsonb,
  '["Backend Developer", "AI Engineer"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'build-rest-api-versioning',
  'API Versioning Project',
  'Versioned routes and backward-compatible schema changes.',
  'Ship API changes without breaking clients.',
  'project', 'SkillOrbit', null, 'Original SkillOrbit project track',
  'Backend Engineering', 'Advanced', 300,
  '["API design", "versioning", "OpenAPI"]'::jsonb,
  '["FastAPI API Foundations"]'::jsonb,
  '["Introduce /v1 prefixes", "Deprecate fields safely"]'::jsonb,
  '["Backend Developer", "Production AI Product Builder"]'::jsonb,
  'Free project track', false, 'pending'
),
(
  'supabase-row-level-security',
  'Supabase Row Level Security',
  'Official RLS policies for learner data and admin catalog writes.',
  'Secure Postgres at the row level.',
  'documentation', 'Supabase', 'https://supabase.com/docs/guides/auth/row-level-security',
  'Supabase documentation', 'Backend Engineering', 'Intermediate', 90,
  '["Supabase", "RLS", "Postgres"]'::jsonb, '[]'::jsonb,
  '["Write select/insert policies", "Test policies per role"]'::jsonb,
  '["Backend Developer"]'::jsonb,
  'Official documentation', true, 'pending'
),
(
  'real-python-async-io',
  'Real Python Async IO',
  'Async tutorial for moving from sync scripts to async FastAPI services.',
  'Async mental model for backend devs.',
  'tutorial', 'Real Python', 'https://realpython.com/async-io-python/',
  'Real Python article', 'Backend Engineering', 'Intermediate', 120,
  '["asyncio", "Python", "concurrency"]'::jsonb,
  '["Python Foundations for Builders"]'::jsonb,
  '["Explain event loops", "Debug blocking calls"]'::jsonb,
  '["Backend Developer"]'::jsonb,
  'External · free article', true, 'pending'
),
(
  'structured-outputs-with-llms',
  'Structured Outputs with LLMs',
  'JSON schema constrained generation for reliable UI and agent handoffs.',
  'Get parseable model output every time.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Generative AI', 'Intermediate', 190,
  '["structured output", "JSON schema", "LLMs"]'::jsonb,
  '["Prompt Engineering for Products"]'::jsonb,
  '["Define response schemas", "Retry on parse failures"]'::jsonb,
  '["Generative AI Builder", "AI Engineer"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'image-generation-product-patterns',
  'Image Generation in Products',
  'Moderation gates, cost caps, and Mesh API media routes.',
  'Add images without blowing the budget.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Generative AI', 'Intermediate', 170,
  '["image generation", "moderation", "Mesh API"]'::jsonb,
  '["Prompt Engineering for Products"]'::jsonb,
  '["Gate unsafe prompts", "Cache repeated generations"]'::jsonb,
  '["Generative AI Builder", "Production AI Product Builder"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'langgraph-quickstart',
  'LangGraph Quickstart',
  'Official LangGraph intro for stateful multi-step agents.',
  'Orchestrate agents as explicit graphs.',
  'documentation', 'LangChain', 'https://langchain-ai.github.io/langgraph/tutorials/introduction/',
  'LangGraph documentation', 'Agentic AI', 'Intermediate', 140,
  '["LangGraph", "agents", "orchestration"]'::jsonb,
  '["Agentic Workflows with LangGraph"]'::jsonb,
  '["Model agent steps as nodes", "Persist graph state"]'::jsonb,
  '["Generative AI Builder", "AI Engineer"]'::jsonb,
  'Official documentation', true, 'pending'
),
(
  'fine-tuning-vs-rag-decision',
  'Fine-Tuning vs RAG',
  'When retrieval beats fine-tuning for product knowledge and freshness.',
  'Pick the right customization lever.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Generative AI', 'Intermediate', 150,
  '["RAG", "fine-tuning", "retrieval"]'::jsonb,
  '["Building Production RAG Systems"]'::jsonb,
  '["Compare freshness tradeoffs", "Prototype with RAG first"]'::jsonb,
  '["Generative AI Builder", "AI Engineer"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'deeplearning-ai-genai-course',
  'Generative AI with LLMs (overview)',
  'Curated DeepLearning.AI course listing for Gen AI fundamentals.',
  'Short course path for Gen AI basics.',
  'external_course', 'DeepLearning.AI', 'https://www.deeplearning.ai/courses/generative-ai-with-llms/',
  'DeepLearning.AI course listing', 'Generative AI', 'Beginner', 480,
  '["generative AI", "LLMs", "RLHF"]'::jsonb, '[]'::jsonb,
  '["Follow a structured Gen AI syllabus"]'::jsonb,
  '["Generative AI Builder", "Data/ML Foundations"]'::jsonb,
  'External · free tier', true, 'pending'
),
(
  'multimodal-agent-sketch',
  'Multimodal Agent Sketch',
  'Project: moderate uploads, retrieve, and respond with grounded catalog links.',
  'Prototype a multimodal copilot.',
  'project', 'SkillOrbit', null, 'Original SkillOrbit project track',
  'Generative AI', 'Advanced', 420,
  '["multimodal", "moderation", "RAG"]'::jsonb,
  '["Structured Outputs with LLMs"]'::jsonb,
  '["Moderate uploads", "Return grounded next steps"]'::jsonb,
  '["Generative AI Builder", "Production AI Product Builder"]'::jsonb,
  'Free project track', false, 'pending'
),
(
  'numpy-linear-algebra-refresh',
  'NumPy Linear Algebra Refresh',
  'Vectors and dot products—the minimum math for embeddings intuition.',
  'Math intuition behind embeddings.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Data Foundations', 'Beginner', 200,
  '["NumPy", "linear algebra", "vectors"]'::jsonb,
  '["Python Foundations for Builders"]'::jsonb,
  '["Compute dot products", "Relate distance to similarity"]'::jsonb,
  '["Data/ML Foundations", "AI Engineer"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'scikit-learn-user-guide',
  'scikit-learn User Guide',
  'Official sklearn guide for pipelines and cross-validation.',
  'Classical ML with a consistent API.',
  'documentation', 'scikit-learn', 'https://scikit-learn.org/stable/user_guide.html',
  'scikit-learn documentation', 'Data Foundations', 'Intermediate', 180,
  '["scikit-learn", "ML", "pipelines"]'::jsonb,
  '["ML Model Evaluation Basics"]'::jsonb,
  '["Build a sklearn pipeline", "Interpret basic metrics"]'::jsonb,
  '["Data/ML Foundations"]'::jsonb,
  'Official documentation', true, 'pending'
),
(
  'feature-engineering-tabular',
  'Feature Engineering for Tabular Data',
  'Encoding, scaling, and leakage avoidance for tabular datasets.',
  'Prepare data models actually consume.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Data Foundations', 'Intermediate', 240,
  '["feature engineering", "pandas", "encoding"]'::jsonb,
  '["Pandas Data Wrangling"]'::jsonb,
  '["Detect target leakage", "Encode categoricals"]'::jsonb,
  '["Data/ML Foundations", "AI Engineer"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'kaggle-intro-ml',
  'Intro to Machine Learning',
  'Curated Kaggle micro-course for hands-on sklearn practice.',
  'Hands-on ML in notebooks.',
  'external_course', 'Kaggle', 'https://www.kaggle.com/learn/intro-to-machine-learning',
  'Kaggle Learn course', 'Data Foundations', 'Beginner', 300,
  '["Kaggle", "sklearn", "notebooks"]'::jsonb, '[]'::jsonb,
  '["Complete notebook exercises"]'::jsonb,
  '["Data/ML Foundations"]'::jsonb,
  'External · free', true, 'pending'
),
(
  'data-storytelling-for-ml',
  'Data Storytelling for ML Results',
  'Communicate model outcomes with clear charts and honest limitations.',
  'Make ML findings actionable.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Data Foundations', 'Beginner', 160,
  '["communication", "visualization", "ML"]'::jsonb,
  '["ML Model Evaluation Basics"]'::jsonb,
  '["Frame metrics in business terms", "Document limitations"]'::jsonb,
  '["Data/ML Foundations", "Production AI Product Builder"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'observability-for-llm-apps',
  'Observability for LLM Apps',
  'Trace IDs, latency budgets, and Mesh API dashboard workflows.',
  'See what your agent did in production.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'AI Product Building', 'Intermediate', 180,
  '["observability", "tracing", "Mesh API"]'::jsonb,
  '["Behavioral Analytics for Learners"]'::jsonb,
  '["Attach trace IDs", "Review Mesh dashboard runs"]'::jsonb,
  '["Production AI Product Builder", "AI Engineer"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'render-deploy-guide',
  'Render Deploy Guide',
  'Official Render docs for web services and health checks.',
  'Ship FastAPI to a public URL.',
  'documentation', 'Render', 'https://render.com/docs/deploy-fastapi',
  'Render documentation', 'AI Product Building', 'Beginner', 60,
  '["Render", "deployment", "FastAPI"]'::jsonb,
  '["Deploy an AI API to Production"]'::jsonb,
  '["Configure env vars", "Verify health endpoint"]'::jsonb,
  '["Production AI Product Builder", "Backend Developer"]'::jsonb,
  'Official documentation', true, 'pending'
),
(
  'incident-response-for-ai',
  'Incident Response for AI Features',
  'Playbook for bad recommendations, model outages, and rollback.',
  'Operate AI features like real software.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'AI Product Building', 'Advanced', 150,
  '["incident response", "rollback", "SLOs"]'::jsonb,
  '["Observability for LLM Apps"]'::jsonb,
  '["Disable generation quickly", "Postmortem with retrieval logs"]'::jsonb,
  '["Production AI Product Builder"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'privacy-for-behavioral-data',
  'Privacy for Behavioral Data',
  'Consent copy, retention limits, and metadata bounding for activity tracking.',
  'Track behavior ethically.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'AI Product Building', 'Intermediate', 140,
  '["privacy", "consent", "analytics"]'::jsonb,
  '["Behavioral Analytics for Learners"]'::jsonb,
  '["Write clear consent text", "Bound event metadata"]'::jsonb,
  '["Production AI Product Builder"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'launch-checklist-saas-mvp',
  'SaaS MVP Launch Checklist',
  'Project: public URL, monitoring, README, and demo video for judges.',
  'Launch like a product team.',
  'project', 'SkillOrbit', null, 'Original SkillOrbit project track',
  'AI Product Building', 'Intermediate', 240,
  '["launch", "SaaS", "demo"]'::jsonb,
  '["Deploy an AI API to Production"]'::jsonb,
  '["Ship public URL", "Record demo video"]'::jsonb,
  '["Production AI Product Builder"]'::jsonb,
  'Free project track', false, 'pending'
),
(
  'onboarding-ux-for-ai-products',
  'Onboarding UX for AI Products',
  'Goal selection, first recommendation, and empty-state copy patterns.',
  'First session that feels intentional.',
  'tutorial', 'SkillOrbit', null, 'Original SkillOrbit tutorial',
  'AI Product Building', 'Beginner', 120,
  '["UX", "onboarding", "copywriting"]'::jsonb, '[]'::jsonb,
  '["Write goal-selection copy", "Celebrate first recommendation"]'::jsonb,
  '["Production AI Product Builder"]'::jsonb,
  'Free open tutorial', false, 'pending'
)
on conflict (slug) do nothing;
