-- Final catalog expansion to 80 resources. Run after 013_catalog_to_80.sql.

insert into public.products (
  slug, title, description, short_summary, content_type, provider, source_url,
  license_info, category, difficulty, duration_minutes, skills, prerequisites,
  learning_outcomes, career_goals, price_label, is_external, vector_sync_status
)
values
(
  'async-python-patterns',
  'Async Python Patterns',
  'Concurrency primitives for APIs and agents without blocking the event loop.',
  'Write responsive Python services with asyncio.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Backend Development', 'Intermediate', 240,
  '["asyncio", "concurrency", "Python"]'::jsonb, '["Python Foundations for Builders"]'::jsonb,
  '["Use async/await safely", "Avoid blocking calls in handlers"]'::jsonb,
  '["Backend Developer", "AI Engineer"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'graphql-api-design',
  'GraphQL API Design Basics',
  'Schema design, resolvers, and when GraphQL beats REST for product APIs.',
  'Model flexible APIs for evolving frontends.',
  'tutorial', 'SkillOrbit', null, 'Original SkillOrbit tutorial',
  'Backend Development', 'Intermediate', 180,
  '["GraphQL", "API design", "schemas"]'::jsonb, '["FastAPI API Foundations"]'::jsonb,
  '["Define a minimal schema", "Compare GraphQL vs REST tradeoffs"]'::jsonb,
  '["Backend Developer"]'::jsonb,
  'Free open tutorial', false, 'pending'
),
(
  'kubernetes-for-developers',
  'Kubernetes for Application Developers',
  'Deployments, services, and health checks for containerized APIs.',
  'Ship backends that scale beyond a single VM.',
  'documentation', 'Kubernetes', 'https://kubernetes.io/docs/tutorials/kubernetes-basics/',
  'Kubernetes documentation', 'Backend Development', 'Advanced', 300,
  '["Kubernetes", "containers", "deployments"]'::jsonb, '["Deploy FastAPI to Render"]'::jsonb,
  '["Map pods to services", "Configure liveness probes"]'::jsonb,
  '["Backend Developer", "Production AI Product Builder"]'::jsonb,
  'Official documentation', true, 'pending'
),
(
  'prompt-chaining-patterns',
  'Prompt Chaining Patterns',
  'Break complex LLM tasks into verifiable steps with structured outputs.',
  'Chain prompts without losing grounding.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Generative AI', 'Intermediate', 210,
  '["prompt engineering", "chains", "LLM workflows"]'::jsonb,
  '["Prompt Engineering for Products"]'::jsonb,
  '["Design a three-step chain", "Validate intermediate JSON"]'::jsonb,
  '["Generative AI Builder", "AI Engineer"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'multimodal-embeddings-intro',
  'Multimodal Embeddings Introduction',
  'When and how to embed images, audio, and text for retrieval systems.',
  'Extend RAG beyond plain text documents.',
  'tutorial', 'SkillOrbit', null, 'Original SkillOrbit tutorial',
  'Generative AI', 'Advanced', 180,
  '["embeddings", "multimodal", "retrieval"]'::jsonb,
  '["Vector Search with Qdrant"]'::jsonb,
  '["Pick a multimodal use case", "Sketch an indexing pipeline"]'::jsonb,
  '["Generative AI Builder", "AI Engineer"]'::jsonb,
  'Free open tutorial', false, 'pending'
),
(
  'feature-stores-overview',
  'Feature Stores Overview',
  'Online/offline features for ML products that need fresh signals.',
  'Serve consistent features in training and production.',
  'documentation', 'Feast', 'https://docs.feast.dev/',
  'Feast documentation', 'Data Foundations', 'Intermediate', 150,
  '["feature stores", "ML ops", "data engineering"]'::jsonb,
  '["Data Pipelines for ML"]'::jsonb,
  '["Explain train-serve skew", "Outline a minimal feature store"]'::jsonb,
  '["Data/ML Foundations", "AI Engineer"]'::jsonb,
  'Official documentation', true, 'pending'
),
(
  'statistics-for-ml-builders',
  'Statistics for ML Builders',
  'Distributions, confidence, and practical intuition without heavy math.',
  'Reason about data before you tune models.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Data Foundations', 'Beginner', 240,
  '["statistics", "probability", "hypothesis testing"]'::jsonb, '[]'::jsonb,
  '["Interpret variance in metrics", "Spot misleading aggregates"]'::jsonb,
  '["Data/ML Foundations"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'ab-testing-for-ai-features',
  'A/B Testing for AI Features',
  'Ship model changes with guardrails and statistically sound experiments.',
  'Measure whether AI actually helps users.',
  'project', 'SkillOrbit', null, 'Original SkillOrbit project track',
  'AI Product Building', 'Intermediate', 300,
  '["A/B testing", "experimentation", "metrics"]'::jsonb,
  '["ML Model Evaluation Basics"]'::jsonb,
  '["Define success metrics", "Plan a safe rollout"]'::jsonb,
  '["Production AI Product Builder"]'::jsonb,
  'Free project track', false, 'pending'
),
(
  'incident-response-for-ai-apis',
  'Incident Response for AI APIs',
  'Runbooks for latency spikes, bad outputs, and provider outages.',
  'Keep AI features reliable under pressure.',
  'tutorial', 'SkillOrbit', null, 'Original SkillOrbit tutorial',
  'AI Product Building', 'Intermediate', 120,
  '["incident response", "SRE", "on-call"]'::jsonb,
  '["Deploy an AI API to Production"]'::jsonb,
  '["Write a severity matrix", "Draft a rollback checklist"]'::jsonb,
  '["Production AI Product Builder", "Backend Developer"]'::jsonb,
  'Free open tutorial', false, 'pending'
),
(
  'redis-caching-for-apis',
  'Redis Caching for APIs',
  'Cache embeddings, sessions, and hot catalog reads responsibly.',
  'Cut latency without stale recommendations.',
  'documentation', 'Redis', 'https://redis.io/docs/latest/develop/get-started/',
  'Redis documentation', 'Backend Development', 'Intermediate', 120,
  '["Redis", "caching", "performance"]'::jsonb,
  '["FastAPI API Foundations"]'::jsonb,
  '["Pick cache keys", "Set TTL policies"]'::jsonb,
  '["Backend Developer"]'::jsonb,
  'Official documentation', true, 'pending'
),
(
  'agent-memory-patterns',
  'Agent Memory Patterns',
  'Short-term context vs long-term learner profiles in copilots.',
  'Design memory that respects privacy and grounding.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'Agentic AI', 'Advanced', 210,
  '["agent memory", "profiles", "context windows"]'::jsonb,
  '["LangChain Expression Language"]'::jsonb,
  '["Separate session vs profile memory", "Avoid ungrounded recall"]'::jsonb,
  '["AI Engineer", "Generative AI Builder"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'build-rag-evaluation-set',
  'Build a RAG Evaluation Set',
  'Curate question-answer pairs to regression-test retrieval quality.',
  'Catch retrieval regressions before judges do.',
  'project', 'SkillOrbit', null, 'Original SkillOrbit project track',
  'Agentic AI', 'Intermediate', 240,
  '["RAG evaluation", "benchmarks", "retrieval"]'::jsonb,
  '["Build a RAG Application"]'::jsonb,
  '["Author 20 eval queries", "Score top-k hit rate"]'::jsonb,
  '["AI Engineer", "Generative AI Builder"]'::jsonb,
  'Free project track', false, 'pending'
),
(
  'sql-window-functions',
  'SQL Window Functions for Analytics',
  'Rolling metrics and cohort views for learning analytics dashboards.',
  'Answer product questions with SQL, not guesswork.',
  'tutorial', 'SkillOrbit', null, 'Original SkillOrbit tutorial',
  'Data Foundations', 'Intermediate', 150,
  '["SQL", "window functions", "analytics"]'::jsonb,
  '["SQL for Product Builders"]'::jsonb,
  '["Compute weekly active learners", "Build a streak query"]'::jsonb,
  '["Data/ML Foundations", "Production AI Product Builder"]'::jsonb,
  'Free open tutorial', false, 'pending'
),
(
  'openapi-contract-testing',
  'OpenAPI Contract Testing',
  'Keep frontend, agents, and docs aligned with your API schema.',
  'Prevent silent API drift in fast-moving teams.',
  'tutorial', 'SkillOrbit', null, 'Original SkillOrbit tutorial',
  'Backend Development', 'Intermediate', 120,
  '["OpenAPI", "contract testing", "FastAPI"]'::jsonb,
  '["FastAPI API Foundations"]'::jsonb,
  '["Generate schemas from routes", "Add a contract test"]'::jsonb,
  '["Backend Developer"]'::jsonb,
  'Free open tutorial', false, 'pending'
),
(
  'cost-aware-llm-routing',
  'Cost-Aware LLM Routing',
  'Route cheap models for retrieval prep and premium models for final copy.',
  'Control Mesh spend without sacrificing quality.',
  'original_module', 'SkillOrbit', null, 'Original SkillOrbit module',
  'AI Product Building', 'Advanced', 180,
  '["cost optimization", "model routing", "Mesh API"]'::jsonb,
  '["Deploy an AI API to Production"]'::jsonb,
  '["Define routing rules", "Log cost per recommendation"]'::jsonb,
  '["Production AI Product Builder", "AI Engineer"]'::jsonb,
  'Free learning module', false, 'pending'
),
(
  'learner-analytics-dashboard',
  'Learner Analytics Dashboard Project',
  'Visualize signals, streaks, and path completion for your own copilot.',
  'Turn events into product insight.',
  'project', 'SkillOrbit', null, 'Original SkillOrbit project track',
  'AI Product Building', 'Intermediate', 300,
  '["analytics", "dashboards", "learning metrics"]'::jsonb,
  '["Onboarding UX for AI Products"]'::jsonb,
  '["Ship streak + weekly goal UI", "Tie charts to real events"]'::jsonb,
  '["Production AI Product Builder"]'::jsonb,
  'Free project track', false, 'pending'
)
on conflict (slug) do nothing;
